
export const oilItems = 
[
    {
        Items: 1,
        Roman_Name: "Adrak Oil",
        Price: 110,
        MOQ: 30,
        Image : require('../../assets/oilImages/Adrak Oil.JPG'),
      },
      {
        Items: 2,
        Roman_Name: "Ajwain Oil",
        Price: 190,
        MOQ: 30,
        Image : require('../../assets/oilImages/Ajwain Oil.JPG'),
      },
      {
        Items: 9,
        Roman_Name: "Akhrot Oil",
        Price: 170,
        MOQ: 30,
        Image : require('../../assets/oilImages/Akhrot Oil.JPG'),
      },
      {
        Items: 6,
        Roman_Name: "Alsi Oil",
        Price: 80,
        MOQ: 30,
        Image : require('../../assets/oilImages/Alsi Oil 30.JPG'),
      },
      {
        Items: 7,
        Roman_Name: "Alsi Oil",
        Price: 250,
        MOQ: 125,
        Image : require('../../assets/oilImages/Alsi Oil 125.JPG'),
      },
      {
        Items: 4,
        Roman_Name: "Amla Oil",
        Price: 220,
        MOQ: 125,
        Image : require('../../assets/oilImages/Amla Oil.JPG'),
      },
      {
        Items: 8,
        Roman_Name: "Amla, Reetha, Sekakai Oil",
        Price: 240,
        MOQ: 125,
        Image : require('../../assets/oilImages/Amla, Reetha, Sekakai Oil.JPG'),
      },
      {
        Items: 10,
        Roman_Name: "Babchi Oil",
        Price: 200,
        MOQ: 30,
        Image : require('../../assets/oilImages/Babchi Oil.JPG'),
      },
      {
        Items: 12,
        Roman_Name: "Baboona Oil",
        Price: 80,
        MOQ: 30,
        Image : require('../../assets/oilImages/Baboona Oil.JPG'),
      },
      {
        Items: 14,
        Roman_Name: "Badam (Sheerin) Oil",
        Price: 160,
        MOQ: 30,
        Image : require('../../assets/oilImages/Badam (Sheerin) Oil 30.JPG'),
      },
      {
        Items: 15,
        Roman_Name: "Badam (Sheerin) Oil",
        Price: 550,
        MOQ: 125,
        Image : require('../../assets/oilImages/Badam (Sheerin) Oil 125.JPG'),
      },
      {
        Items: 13,
        Roman_Name: "Banafsha Oil",
        Price: 120,
        MOQ: 30,
        Image : require('../../assets/oilImages/Banafsha Oil.JPG'),
      },
      {
        Items: 17,
        Roman_Name: "Bdam (Tulkh) Oil",
        Price: 210,
        MOQ: 30,
        Image : require('../../assets/oilImages/Bdam (Tulkh) Oil.JPG'),
      },
      {
        Items: 11,
        Roman_Name: "Behar Booti Oil",
        Price: 240,
        MOQ: 30,
        Image : require('../../assets/oilImages/Behar Booti Oil.JPG'),
      },
      {
        Items: 16,
        Roman_Name: "Beza Murhg Oil",
        Price: 280,
        MOQ: 30,
        Image : require('../../assets/oilImages/Beza Murhg Oil.JPG'),

      },
      {
        Items: 39,
        Roman_Name: "Castor Oil",
        Price: 50,
        MOQ: 30,
        Image : require('../../assets/oilImages/Castor Oil 30.JPG'),
      },
      {
        Items: 40,
        Roman_Name: "Castor Oil",
        Price: 150,
        MOQ: 120,
        Image : require('../../assets/oilImages/Castor Oil 120.JPG'),
      },
      {
        Items: 22,
        Roman_Name: "Chaaro Magaz Oil",
        Price: 130,
        MOQ: 30,
        Image : require('../../assets/oilImages/Chaaro Magaz.JPG'),
      },
      {
        Items: 23,
        Roman_Name: "Chanbeli Oil",
        Price: 90,
        MOQ: 30,
        Image : require('../../assets/oilImages/Chanbeli Oil.JPG'),        
      },
      {
        Items: 27,
        Roman_Name: "Dar Cheeni Oil",
        Price: 170,
        MOQ: 30,
        Image : require('../../assets/oilImages/Dar Cheeni Oil.JPG'),  
      },
      {
        Items: 26,
        Roman_Name: "Dhaniya Oil",
        Price: 170,
        MOQ: 30,
        Image : require('../../assets/oilImages/Dhaniya Oil.JPG'),  
      },
      {
        Items: 3,
        Roman_Name: "Elaichi Oil",
        Price: 250,
        MOQ: 30,
        Image : require('../../assets/oilImages/Elaichi Oil.JPG'),
      },
      {
        Items: 50,
        Roman_Name: "Fish Oil",
        Price: 110,
        MOQ: 30,
        Image : require('../../assets/oilImages/Fish Oil.JPG'),
      },
      {
        Items: 47,
        Roman_Name: "Garlic Oil",
        Price: 100,
        MOQ: 30,
        Image : require('../../assets/oilImages/Garlic Oil.JPG'),
      },
      {
        Items: 43,
        Roman_Name: "Glycerin",
        Price: 45,
        MOQ: 30,
        Image : require('../../assets/oilImages/Glycerin30.JPG'),
      },
      {
        Items: 44,
        Roman_Name: "Glycerin",
        Price: 130,
        MOQ: 120,
        Image : require('../../assets/oilImages/Glycerin.JPG'),
      },
      {
        Items: 42,
        Roman_Name: "Gul Oil",
        Price: 70,
        MOQ: 30,
        Image : require('../../assets/oilImages/Gul Oil.JPG'),
      },
      {
        Items: 5,
        Roman_Name: "Indrain Oil",
        Price: 130,
        MOQ: 30,
        Image : require('../../assets/oilImages/Indrain Oil.JPG'),
      },
      {
        Items: 36,
        Roman_Name: "Kaahu Oil",
        Price: 120,
        MOQ: 30,
        Image : require('../../assets/oilImages/Kaahu Oil.JPG'),        
      },
      {
        Items: 41,
        Roman_Name: "Kaddo Oil",
        Price: 150,
        MOQ: 30,
        Image : require('../../assets/oilImages/Kaddo Oil.JPG'),        
      },
      {
        Items: 37,
        Roman_Name: "Kalonji Oil",
        Price: 140,
        MOQ: 30,
        Image : require('../../assets/oilImages/Kalonji Oil30.JPG'),        
      },
      {
        Items: 38,
        Roman_Name: "Kalonji Oil",
        Price: 500,
        MOQ: 125,
        Image : require('../../assets/oilImages/Kalonji Oil125.JPG'),        
      },
      {
        Items: 25,
        Roman_Name: "Khashkhash Oil",
        Price: 90,
        MOQ: 30,
        Image : require('../../assets/oilImages/Khashkhash Oil.JPG'),        
      },
      {
        Items: 24,
        Roman_Name: "Khubani Oil",
        Price: 170,
        MOQ: 30,
        Image : require('../../assets/oilImages/Khubani Oil.JPG'),        
      },
      {
        Items: 45,
        Roman_Name: "Laboob Saba Oil",
        Price: 150,
        MOQ: 30,
        Image : require('../../assets/oilImages/Laboob Saba Oil.JPG'),        
      },
      {
        Items: 46,
        Roman_Name: "Lemon Oil",
        Price: 170,
        MOQ: 30,
        Image : require('../../assets/oilImages/Lemon Oil.JPG'),        
      },
      {
        Items: 48,
        Roman_Name: "Long Oil",
        Price: 400,
        MOQ: 30,
        Image : require('../../assets/oilImages/Long Oil.JPG'),        
      },
      {
        Items: 51,
        Roman_Name: "Malkangni Oil",
        Price: 270,
        MOQ: 30,
        Image : require('../../assets/oilImages/Malkangni Oil.JPG'),        
      },
      {
        Items: 52,
        Roman_Name: "Mong Phali Oil",
        Price: 90,
        MOQ: 30,
        Image : require('../../assets/oilImages/Mong Phali Oil.JPG'),
      },
      {
        Items: 53,
        Roman_Name: "Neem (Niboli) Oil",
        Price: 110,
        MOQ: 30,
        Image : require('../../assets/oilImages/Neem.JPG'),
      },
      {
        Items: 54,
        Roman_Name: "Orange Oil",
        Price: 180,
        MOQ: 30,
        Image : require('../../assets/oilImages/Orange Oil.JPG'),
      },
      {
        Items: 18,
        Roman_Name: "Pista Oil",
        Price: 400,
        MOQ: 30,
        Image : require('../../assets/oilImages/Pista Oil.JPG'),
      },
      {
        Items: 19,
        Roman_Name: "Podina Oil",
        Price: 290,
        MOQ: 30,
        Image : require('../../assets/oilImages/Podina Oil.JPG'),
      },
      {
        Items: 28,
        Roman_Name: "Rai Oil",
        Price: 110,
        MOQ: 30,
        Image : require('../../assets/oilImages/Rai Oil.JPG'),
      },
      {
        Items: 32,
        Roman_Name: "Safeda Oil",
        Price: 180,
        MOQ: 30,
        Image : require('../../assets/oilImages/Safeda Oil.JPG'),
      },
      {
        Items: 33,
        Roman_Name: "Sandal Oil",
        Price: 170,
        MOQ: 30,
        Image : require('../../assets/oilImages/Sandal Oil.JPG'),
      },
      {
        Items: 31,
        Roman_Name: "Sonf Oil",
        Price: 240,
        MOQ: 30,
        Image : require('../../assets/oilImages/Sonf Oil.JPG'),
      },
      {
        Items: 21,
        Roman_Name: "Tar Pin Oil",
        Price: 80,
        MOQ: 30,
        Image : require('../../assets/oilImages/Tar Pin Oil.JPG'),
      },
      {
        Items: 20,
        Roman_Name: "Tara Meera Oil",
        Price: 55,
        MOQ: 30,
        Image : require('../../assets/oilImages/Tara Meera Oil.JPG'),
      },
      {
        Items: 49,
        Roman_Name: "Thukam Muli Oil",
        Price: 100,
        MOQ: 30,
        Image : require('../../assets/oilImages/Muli.JPG'),
      },
      {
        Items: 34,
        Roman_Name: "Til Oil",
        Price: 50,
        MOQ: 30,
        Image : require('../../assets/oilImages/Til Oil30.JPG'),
      },
      {
        Items: 35,
        Roman_Name: "Til Oil",
        Price: 150,
        MOQ: 120,
        Image : require('../../assets/oilImages/Til Oil120.JPG'),
      },
      {
        Items: 29,
        Roman_Name: "Zetoon Oil",
        Price: 70,
        MOQ: 30,
        Image : require('../../assets/oilImages/Zetoon Oil30.JPG'),
      },
      {
        Items: 30,
        Roman_Name: "Zetoon Oil",
        Price: 240,
        MOQ: 120,
        Image : require('../../assets/oilImages/Zetoon Oil120.JPG'),
      }
  ]